version: '3'

services:
  fastapi-app:
    image: fastapi
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - '8000:8000'
    volumes:
      - ./data:/white-win-api/data
