version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    #외부와 소통하는 경우에는 ports로 포트 설정.
    ports:
      - '80:80/tcp'
      - '443:443'
    volumes:
      #docker-compose.yml과 같은 레벨에 둔 nginx.conf를 mount.
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi-app
  fastapi-app:
    image: fastapi
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - '8000:8000'
    volumes:
      - ./data:/white-win-api/data
